In [1]:
pip install tabula-py

Requirement already satisfied: tabula-py in /Users/miriamcorona/opt/anaconda3/lib/python3.9/site-packages (2.3.0)
Requirement already satisfied: pandas>=0.25.3 in /Users/miriamcorona/opt/anaconda3/lib/python3.9/site-packages (from tabula-py) (1.3.4)
Requirement already satisfied: distro in /Users/miriamcorona/opt/anaconda3/lib/python3.9/site-packages (from tabula-py) (1.7.0)
Requirement already satisfied: numpy in /Users/miriamcorona/opt/anaconda3/lib/python3.9/site-packages (from tabula-py) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/miriamcorona/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Users/miriamcorona/opt/anaconda3/lib/python3.9/site-packages (from pandas>=0.25.3->tabula-py) (2021.3)
Requirement already satisfied: six>=1.5 in /Users/miriamcorona/opt/anaconda3/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [55]:
import tabula as tb
import pandas as pd
import re


file = '/Users/miriamcorona/Desktop/pdfs/beprices.pdf'
data = tb.read_pdf(file, area = (80, 0, 300, 800),  pages = '1', guess=False)

print(data)

Got stderr: Mar 08, 2022 11:48:37 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'Times-Bold' for 'TimesNewRoman-Bold'

[    $ Per Lb.     70     71     72     73     74     75     76     77     78  \
0        0.45  63.33  64.07  64.80  65.53  66.27  67.00  67.73  68.47  69.20
1        0.46  63.60  64.33  65.07  65.80  66.53  67.27  68.00  68.73  69.47
2        0.47  63.87  64.60  65.33  66.07  66.80  67.53  68.27  69.00  69.73
3        0.48  64.13  64.87  65.60  66.33  67.07  67.80  68.53  69.27  70.00
4        0.49  64.40  65.13  65.87  66.60  67.33  68.07  68.80  69.53  70.27
5        0.50  64.67  65.40  66.13  66.87  67.60  68.33  69.07  69.80  70.53
6        0.51  64.93  65.67  66.40  67.13  67.87  68.60  69.33  70.07  70.80
7        0.52  65.20  65.93  66.67  67.40  68.13  68.87  69.60  70.33  71.07
8        0.53  65.47  66.20  66.93  67.67  68.40  69.13  69.87  70.60  71.33
9        0.54  65.73  66.47  67.20  67.93  68.67  69.40  70.13  70.87  71.60
10       0.55  66.00  66.73  67.47  68.20  68.93  69.67  70.40  71.13  71.87
11       0.56  66.27  67.00  67.73  68.47  69.20  69.93  70.67  71.40  72.13
12       0.57  66.53  67.27  68.00  68.73  69.47  70.20  70.93  71.67  72.40
13       0.58  66.80  67.53  68.27  69.00  69.73  70.47  71.20  71.93  72.67
14       0.59  67.07  67.80  68.53  69.27  70.00  70.73  71.47  72.20  72.93
15       0.60  67.33  68.07  68.80  69.53  70.27  71.00  71.73  72.47  73.20
16       0.61  67.60  68.33  69.07  69.80  70.53  71.27  72.00  72.73  73.47
17       0.62  67.87  68.60  69.33  70.07  70.80  71.53  72.27  73.00  73.73
18       0.63  68.13  68.87  69.60  70.33  71.07  71.80  72.53  73.27  74.00
19       0.64  68.40  69.13  69.87  70.60  71.33  72.07  72.80  73.53  74.27
20       0.65  68.67  69.40  70.13  70.87  71.60  72.33  73.07  73.80  74.53
21       0.66  68.93  69.67  70.40  71.13  71.87  72.60  73.33  74.07  74.80
22       0.67  69.20  69.93  70.67  71.40  72.13  72.87  73.60  74.33  75.07
23       0.68  69.47  70.20  70.93  71.67  72.40  73.13  73.87  74.60  75.33
24       0.69  69.73  70.47  71.20  71.93  72.67  73.40  74.13  74.87  75.60

    ...     80     81     82     83     84     85     86     87     88     89
0   ...  70.67  71.40  72.13  72.87  73.60  74.33  75.07  75.80  76.53  77.27
1   ...  70.93  71.67  72.40  73.13  73.87  74.60  75.33  76.07  76.80  77.53
2   ...  71.20  71.93  72.67  73.40  74.13  74.87  75.60  76.33  77.07  77.80
3   ...  71.47  72.20  72.93  73.67  74.40  75.13  75.87  76.60  77.33  78.07
4   ...  71.73  72.47  73.20  73.93  74.67  75.40  76.13  76.87  77.60  78.33
5   ...  72.00  72.73  73.47  74.20  74.93  75.67  76.40  77.13  77.87  78.60
6   ...  72.27  73.00  73.73  74.47  75.20  75.93  76.67  77.40  78.13  78.87
7   ...  72.53  73.27  74.00  74.73  75.47  76.20  76.93  77.67  78.40  79.13
8   ...  72.80  73.53  74.27  75.00  75.73  76.47  77.20  77.93  78.67  79.40
9   ...  73.07  73.80  74.53  75.27  76.00  76.73  77.47  78.20  78.93  79.67
10  ...  73.33  74.07  74.80  75.53  76.27  77.00  77.73  78.47  79.20  79.93
11  ...  73.60  74.33  75.07  75.80  76.53  77.27  78.00  78.73  79.47  80.20
12  ...  73.87  74.60  75.33  76.07  76.80  77.53  78.27  79.00  79.73  80.47
13  ...  74.13  74.87  75.60  76.33  77.07  77.80  78.53  79.27  80.00  80.73
14  ...  74.40  75.13  75.87  76.60  77.33  78.07  78.80  79.53  80.27  81.00
15  ...  74.67  75.40  76.13  76.87  77.60  78.33  79.07  79.80  80.53  81.27
16  ...  74.93  75.67  76.40  77.13  77.87  78.60  79.33  80.07  80.80  81.53
17  ...  75.20  75.93  76.67  77.40  78.13  78.87  79.60  80.33  81.07  81.80
18  ...  75.47  76.20  76.93  77.67  78.40  79.13  79.87  80.60  81.33  82.07
19  ...  75.73  76.47  77.20  77.93  78.67  79.40  80.13  80.87  81.60  82.33
20  ...  76.00  76.73  77.47  78.20  78.93  79.67  80.40  81.13  81.87  82.60
21  ...  76.27  77.00  77.73  78.47  79.20  79.93  80.67  81.40  82.13  82.87
22  ...  76.53  77.27  78.00  78.73  79.47  80.20  80.93  81.67  82.40  83.13
23  ...  76.80  77.53  78.27  79.00  79.73  80.47  81.20  81.93  82.67  83.40
24  ...  77.07  77.80  78.53  79.27  80.00  80.73  81.47  82.20  82.93  83.67

[25 rows x 21 columns]]

In [216]:
print(type(data))

<class 'list'>

In [139]:
headers = tb.read_pdf(file, area = (80, 0, 90, 800),  pages = '1')
print(type(headers))

Got stderr: Mar 09, 2022 12:14:59 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'Times-Bold' for 'TimesNewRoman-Bold'

<class 'list'>

In [158]:
pd.set_option('display.max_columns', 500)

In [201]:
df= tb.read_pdf(file, pages = '1', area = (80, 0, 300, 800), columns=[75, 90,105,120,
                                                                      135,155,170,190,
                                                                      200,225,240,255,
                                                                     270,285,295,320,
                                                                     330,340,365,375,
                                                                     395,405,430,435,
                                                                     465,500,535,570,
                                                                     605,640,670,705,
                                                                     740], guess=False,
                pandas_options={'header': None }, stream=True)

Got stderr: Mar 09, 2022 1:14:53 AM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'Times-Bold' for 'TimesNewRoman-Bold'

In [204]:
df

[           0      1   2      3   4      5   6      7   8      9   10     11  \
 0   $ Per Lb.  70.00 NaN  71.00 NaN  72.00 NaN  73.00 NaN  74.00 NaN  75.00
 1        0.45  63.33 NaN  64.07 NaN  64.80 NaN  65.53 NaN  66.27 NaN  67.00
 2        0.46  63.60 NaN  64.33 NaN  65.07 NaN  65.80 NaN  66.53 NaN  67.27
 3        0.47  63.87 NaN  64.60 NaN  65.33 NaN  66.07 NaN  66.80 NaN  67.53
 4        0.48  64.13 NaN  64.87 NaN  65.60 NaN  66.33 NaN  67.07 NaN  67.80
 5        0.49  64.40 NaN  65.13 NaN  65.87 NaN  66.60 NaN  67.33 NaN  68.07
 6        0.50  64.67 NaN  65.40 NaN  66.13 NaN  66.87 NaN  67.60 NaN  68.33
 7        0.51  64.93 NaN  65.67 NaN  66.40 NaN  67.13 NaN  67.87 NaN  68.60
 8        0.52  65.20 NaN  65.93 NaN  66.67 NaN  67.40 NaN  68.13 NaN  68.87
 9        0.53  65.47 NaN  66.20 NaN  66.93 NaN  67.67 NaN  68.40 NaN  69.13
 10       0.54  65.73 NaN  66.47 NaN  67.20 NaN  67.93 NaN  68.67 NaN  69.40
 11       0.55  66.00 NaN  66.73 NaN  67.47 NaN  68.20 NaN  68.93 NaN  69.67
 12       0.56  66.27 NaN  67.00 NaN  67.73 NaN  68.47 NaN  69.20 NaN  69.93
 13       0.57  66.53 NaN  67.27 NaN  68.00 NaN  68.73 NaN  69.47 NaN  70.20
 14       0.58  66.80 NaN  67.53 NaN  68.27 NaN  69.00 NaN  69.73 NaN  70.47
 15       0.59  67.07 NaN  67.80 NaN  68.53 NaN  69.27 NaN  70.00 NaN  70.73
 16       0.60  67.33 NaN  68.07 NaN  68.80 NaN  69.53 NaN  70.27 NaN  71.00
 17       0.61  67.60 NaN  68.33 NaN  69.07 NaN  69.80 NaN  70.53 NaN  71.27
 18       0.62  67.87 NaN  68.60 NaN  69.33 NaN  70.07 NaN  70.80 NaN  71.53
 19       0.63  68.13 NaN  68.87 NaN  69.60 NaN  70.33 NaN  71.07 NaN  71.80
 20       0.64  68.40 NaN  69.13 NaN  69.87 NaN  70.60 NaN  71.33 NaN  72.07
 21       0.65  68.67 NaN  69.40 NaN  70.13 NaN  70.87 NaN  71.60 NaN  72.33
 22       0.66  68.93 NaN  69.67 NaN  70.40 NaN  71.13 NaN  71.87 NaN  72.60
 23       0.67  69.20 NaN  69.93 NaN  70.67 NaN  71.40 NaN  72.13 NaN  72.87
 24       0.68  69.47 NaN  70.20 NaN  70.93 NaN  71.67 NaN  72.40 NaN  73.13
 25       0.69  69.73 NaN  70.47 NaN  71.20 NaN  71.93 NaN  72.67 NaN  73.40

     12     13  14     15  16  17     18  19     20  21     22  23     24  \
 0  NaN  76.00 NaN  77.00 NaN NaN  78.00 NaN  79.00 NaN  80.00 NaN  81.00
 1  NaN  67.73 NaN  68.47 NaN NaN  69.20 NaN  69.93 NaN  70.67 NaN  71.40
 2  NaN  68.00 NaN  68.73 NaN NaN  69.47 NaN  70.20 NaN  70.93 NaN  71.67
 3  NaN  68.27 NaN  69.00 NaN NaN  69.73 NaN  70.47 NaN  71.20 NaN  71.93
 4  NaN  68.53 NaN  69.27 NaN NaN  70.00 NaN  70.73 NaN  71.47 NaN  72.20
 5  NaN  68.80 NaN  69.53 NaN NaN  70.27 NaN  71.00 NaN  71.73 NaN  72.47
 6  NaN  69.07 NaN  69.80 NaN NaN  70.53 NaN  71.27 NaN  72.00 NaN  72.73
 7  NaN  69.33 NaN  70.07 NaN NaN  70.80 NaN  71.53 NaN  72.27 NaN  73.00
 8  NaN  69.60 NaN  70.33 NaN NaN  71.07 NaN  71.80 NaN  72.53 NaN  73.27
 9  NaN  69.87 NaN  70.60 NaN NaN  71.33 NaN  72.07 NaN  72.80 NaN  73.53
 10 NaN  70.13 NaN  70.87 NaN NaN  71.60 NaN  72.33 NaN  73.07 NaN  73.80
 11 NaN  70.40 NaN  71.13 NaN NaN  71.87 NaN  72.60 NaN  73.33 NaN  74.07
 12 NaN  70.67 NaN  71.40 NaN NaN  72.13 NaN  72.87 NaN  73.60 NaN  74.33
 13 NaN  70.93 NaN  71.67 NaN NaN  72.40 NaN  73.13 NaN  73.87 NaN  74.60
 14 NaN  71.20 NaN  71.93 NaN NaN  72.67 NaN  73.40 NaN  74.13 NaN  74.87
 15 NaN  71.47 NaN  72.20 NaN NaN  72.93 NaN  73.67 NaN  74.40 NaN  75.13
 16 NaN  71.73 NaN  72.47 NaN NaN  73.20 NaN  73.93 NaN  74.67 NaN  75.40
 17 NaN  72.00 NaN  72.73 NaN NaN  73.47 NaN  74.20 NaN  74.93 NaN  75.67
 18 NaN  72.27 NaN  73.00 NaN NaN  73.73 NaN  74.47 NaN  75.20 NaN  75.93
 19 NaN  72.53 NaN  73.27 NaN NaN  74.00 NaN  74.73 NaN  75.47 NaN  76.20
 20 NaN  72.80 NaN  73.53 NaN NaN  74.27 NaN  75.00 NaN  75.73 NaN  76.47
 21 NaN  73.07 NaN  73.80 NaN NaN  74.53 NaN  75.27 NaN  76.00 NaN  76.73
 22 NaN  73.33 NaN  74.07 NaN NaN  74.80 NaN  75.53 NaN  76.27 NaN  77.00
 23 NaN  73.60 NaN  74.33 NaN NaN  75.07 NaN  75.80 NaN  76.53 NaN  77.27
 24 NaN  73.87 NaN  74.60 NaN NaN  75.33 NaN  76.07 NaN  76.80 NaN  77.53
 25 NaN  74.13 NaN  74.87 NaN NaN  75.60 NaN  76.33 NaN  77.07 NaN  77.80

        25     26     27     28     29     30     31     32
 0   82.00  83.00  84.00  85.00  86.00  87.00  88.00  89.00
 1   72.13  72.87  73.60  74.33  75.07  75.80  76.53  77.27
 2   72.40  73.13  73.87  74.60  75.33  76.07  76.80  77.53
 3   72.67  73.40  74.13  74.87  75.60  76.33  77.07  77.80
 4   72.93  73.67  74.40  75.13  75.87  76.60  77.33  78.07
 5   73.20  73.93  74.67  75.40  76.13  76.87  77.60  78.33
 6   73.47  74.20  74.93  75.67  76.40  77.13  77.87  78.60
 7   73.73  74.47  75.20  75.93  76.67  77.40  78.13  78.87
 8   74.00  74.73  75.47  76.20  76.93  77.67  78.40  79.13
 9   74.27  75.00  75.73  76.47  77.20  77.93  78.67  79.40
 10  74.53  75.27  76.00  76.73  77.47  78.20  78.93  79.67
 11  74.80  75.53  76.27  77.00  77.73  78.47  79.20  79.93
 12  75.07  75.80  76.53  77.27  78.00  78.73  79.47  80.20
 13  75.33  76.07  76.80  77.53  78.27  79.00  79.73  80.47
 14  75.60  76.33  77.07  77.80  78.53  79.27  80.00  80.73
 15  75.87  76.60  77.33  78.07  78.80  79.53  80.27  81.00
 16  76.13  76.87  77.60  78.33  79.07  79.80  80.53  81.27
 17  76.40  77.13  77.87  78.60  79.33  80.07  80.80  81.53
 18  76.67  77.40  78.13  78.87  79.60  80.33  81.07  81.80
 19  76.93  77.67  78.40  79.13  79.87  80.60  81.33  82.07
 20  77.20  77.93  78.67  79.40  80.13  80.87  81.60  82.33
 21  77.47  78.20  78.93  79.67  80.40  81.13  81.87  82.60
 22  77.73  78.47  79.20  79.93  80.67  81.40  82.13  82.87
 23  78.00  78.73  79.47  80.20  80.93  81.67  82.40  83.13
 24  78.27  79.00  79.73  80.47  81.20  81.93  82.67  83.40
 25  78.53  79.27  80.00  80.73  81.47  82.20  82.93  83.67  ]

In [206]:
df_0 = df[0]

print("type of df :", type(df))
print("type of df_0", type(df_0))

type of df : <class 'list'>
type of df_0 <class 'pandas.core.frame.DataFrame'>

In [207]:
df_0

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32
0,$ Per Lb.,70.00,NaN,71.00,NaN,72.00,NaN,73.00,NaN,74.00,NaN,75.00,NaN,76.00,NaN,77.00,NaN,NaN,78.00,NaN,79.00,NaN,80.00,NaN,81.00,82.00,83.00,84.00,85.00,86.00,87.00,88.00,89.00
1,0.45,63.33,NaN,64.07,NaN,64.80,NaN,65.53,NaN,66.27,NaN,67.00,NaN,67.73,NaN,68.47,NaN,NaN,69.20,NaN,69.93,NaN,70.67,NaN,71.40,72.13,72.87,73.60,74.33,75.07,75.80,76.53,77.27
2,0.46,63.60,NaN,64.33,NaN,65.07,NaN,65.80,NaN,66.53,NaN,67.27,NaN,68.00,NaN,68.73,NaN,NaN,69.47,NaN,70.20,NaN,70.93,NaN,71.67,72.40,73.13,73.87,74.60,75.33,76.07,76.80,77.53
3,0.47,63.87,NaN,64.60,NaN,65.33,NaN,66.07,NaN,66.80,NaN,67.53,NaN,68.27,NaN,69.00,NaN,NaN,69.73,NaN,70.47,NaN,71.20,NaN,71.93,72.67,73.40,74.13,74.87,75.60,76.33,77.07,77.80
4,0.48,64.13,NaN,64.87,NaN,65.60,NaN,66.33,NaN,67.07,NaN,67.80,NaN,68.53,NaN,69.27,NaN,NaN,70.00,NaN,70.73,NaN,71.47,NaN,72.20,72.93,73.67,74.40,75.13,75.87,76.60,77.33,78.07
5,0.49,64.40,NaN,65.13,NaN,65.87,NaN,66.60,NaN,67.33,NaN,68.07,NaN,68.80,NaN,69.53,NaN,NaN,70.27,NaN,71.00,NaN,71.73,NaN,72.47,73.20,73.93,74.67,75.40,76.13,76.87,77.60,78.33
6,0.50,64.67,NaN,65.40,NaN,66.13,NaN,66.87,NaN,67.60,NaN,68.33,NaN,69.07,NaN,69.80,NaN,NaN,70.53,NaN,71.27,NaN,72.00,NaN,72.73,73.47,74.20,74.93,75.67,76.40,77.13,77.87,78.60
7,0.51,64.93,NaN,65.67,NaN,66.40,NaN,67.13,NaN,67.87,NaN,68.60,NaN,69.33,NaN,70.07,NaN,NaN,70.80,NaN,71.53,NaN,72.27,NaN,73.00,73.73,74.47,75.20,75.93,76.67,77.40,78.13,78.87
8,0.52,65.20,NaN,65.93,NaN,66.67,NaN,67.40,NaN,68.13,NaN,68.87,NaN,69.60,NaN,70.33,NaN,NaN,71.07,NaN,71.80,NaN,72.53,NaN,73.27,74.00,74.73,75.47,76.20,76.93,77.67,78.40,79.13
9,0.53,65.47,NaN,66.20,NaN,66.93,NaN,67.67,NaN,68.40,NaN,69.13,NaN,69.87,NaN,70.60,NaN,NaN,71.33,NaN,72.07,NaN,72.80,NaN,73.53,74.27,75.00,75.73,76.47,77.20,77.93,78.67,79.40
10,0.54,65.73,NaN,66.47,NaN,67.20,NaN,67.93,NaN,68.67,NaN,69.40,NaN,70.13,NaN,70.87,NaN,NaN,71.60,NaN,72.33,NaN,73.07,NaN,73.80,74.53,75.27,76.00,76.73,77.47,78.20,78.93,79.67
11,0.55,66.00,NaN,66.73,NaN,67.47,NaN,68.20,NaN,68.93,NaN,69.67,NaN,70.40,NaN,71.13,NaN,NaN,71.87,NaN,72.60,NaN,73.33,NaN,74.07,74.80,75.53,76.27,77.00,77.73,78.47,79.20,79.93
12,0.56,66.27,NaN,67.00,NaN,67.73,NaN,68.47,NaN,69.20,NaN,69.93,NaN,70.67,NaN,71.40,NaN,NaN,72.13,NaN,72.87,NaN,73.60,NaN,74.33,75.07,75.80,76.53,77.27,78.00,78.73,79.47,80.20
13,0.57,66.53,NaN,67.27,NaN,68.00,NaN,68.73,NaN,69.47,NaN,70.20,NaN,70.93,NaN,71.67,NaN,NaN,72.40,NaN,73.13,NaN,73.87,NaN,74.60,75.33,76.07,76.80,77.53,78.27,79.00,79.73,80.47
14,0.58,66.80,NaN,67.53,NaN,68.27,NaN,69.00,NaN,69.73,NaN,70.47,NaN,71.20,NaN,71.93,NaN,NaN,72.67,NaN,73.40,NaN,74.13,NaN,74.87,75.60,76.33,77.07,77.80,78.53,79.27,80.00,80.73
15,0.59,67.07,NaN,67.80,NaN,68.53,NaN,69.27,NaN,70.00,NaN,70.73,NaN,71.47,NaN,72.20,NaN,NaN,72.93,NaN,73.67,NaN,74.40,NaN,75.13,75.87,76.60,77.33,78.07,78.80,79.53,80.27,81.00
16,0.60,67.33,NaN,68.07,NaN,68.80,NaN,69.53,NaN,70.27,NaN,71.00,NaN,71.73,NaN,72.47,NaN,NaN,73.20,NaN,73.93,NaN,74.67,NaN,75.40,76.13,76.87,77.60,78.33,79.07,79.80,80.53,81.27
17,0.61,67.60,NaN,68.33,NaN,69.07,NaN,69.80,NaN,70.53,NaN,71.27,NaN,72.00,NaN,72.73,NaN,NaN,73.47,NaN,74.20,NaN,74.93,NaN,75.67,76.40,77.13,77.87,78.60,79.33,80.07,80.80,81.53
18,0.62,67.87,NaN,68.60,NaN,69.33,NaN,70.07,NaN,70.80,NaN,71.53,NaN,72.27,NaN,73.00,NaN,NaN,73.73,NaN,74.47,NaN,75.20,NaN,75.93,76.67,77.40,78.13,78.87,79.60,80.33,81.07,81.80
19,0.63,68.13,NaN,68.87,NaN,69.60,NaN,70.33,NaN,71.07,NaN,71.80,NaN,72.53,NaN,73.27,NaN,NaN,74.00,NaN,74.73,NaN,75.47,NaN,76.20,76.93,77.67,78.40,79.13,79.87,80.60,81.33,82.07
20,0.64,68.40,NaN,69.13,NaN,69.87,NaN,70.60,NaN,71.33,NaN,72.07,NaN,72.80,NaN,73.53,NaN,NaN,74.27,NaN,75.00,NaN,75.73,NaN,76.47,77.20,77.93,78.67,79.40,80.13,80.87,81.60,82.33
21,0.65,68.67,NaN,69.40,NaN,70.13,NaN,70.87,NaN,71.60,NaN,72.33,NaN,73.07,NaN,73.80,NaN,NaN,74.53,NaN,75.27,NaN,76.00,NaN,76.73,77.47,78.20,78.93,79.67,80.40,81.13,81.87,82.60
22,0.66,68.93,NaN,69.67,NaN,70.40,NaN,71.13,NaN,71.87,NaN,72.60,NaN,73.33,NaN,74.07,NaN,NaN,74.80,NaN,75.53,NaN,76.27,NaN,77.00,77.73,78.47,79.20,79.93,80.67,81.40,82.13,82.87
23,0.67,69.20,NaN,69.93,NaN,70.67,NaN,71.40,NaN,72.13,NaN,72.87,NaN,73.60,NaN,74.33,NaN,NaN,75.07,NaN,75.80,NaN,76.53,NaN,77.27,78.00,78.73,79.47,80.20,80.93,81.67,82.40,83.13
24,0.68,69.47,NaN,70.20,NaN,70.93,NaN,71.67,NaN,72.40,NaN,73.13,NaN,73.87,NaN,74.60,NaN,NaN,75.33,NaN,76.07,NaN,76.80,NaN,77.53,78.27,79.00,79.73,80.47,81.20,81.93,82.67,83.40
25,0.69,69.73,NaN,70.47,NaN,71.20,NaN,71.93,NaN,72.67,NaN,73.40,NaN,74.13,NaN,74.87,NaN,NaN,75.60,NaN,76.33,NaN,77.07,NaN,77.80,78.53,79.27,80.00,80.73,81.47,82.20,82.93,83.67

In [208]:
new_header = df_0.iloc[0] #grab the first row for the header
df_0 = df_0[1:] #take the data less the header row
df_0.columns = new_header #set the header row as the df header

In [209]:
df_0

,$ Per Lb.,70.0,NaN,71.0,NaN,72.0,NaN,73.0,NaN,74.0,NaN,75.0,NaN,76.0,NaN,77.0,NaN,NaN,78.0,NaN,79.0,NaN,80.0,NaN,81.0,82.0,83.0,84.0,85.0,86.0,87.0,88.0,89.0
1,0.45,63.33,NaN,64.07,NaN,64.80,NaN,65.53,NaN,66.27,NaN,67.00,NaN,67.73,NaN,68.47,NaN,NaN,69.20,NaN,69.93,NaN,70.67,NaN,71.40,72.13,72.87,73.60,74.33,75.07,75.80,76.53,77.27
2,0.46,63.60,NaN,64.33,NaN,65.07,NaN,65.80,NaN,66.53,NaN,67.27,NaN,68.00,NaN,68.73,NaN,NaN,69.47,NaN,70.20,NaN,70.93,NaN,71.67,72.40,73.13,73.87,74.60,75.33,76.07,76.80,77.53
3,0.47,63.87,NaN,64.60,NaN,65.33,NaN,66.07,NaN,66.80,NaN,67.53,NaN,68.27,NaN,69.00,NaN,NaN,69.73,NaN,70.47,NaN,71.20,NaN,71.93,72.67,73.40,74.13,74.87,75.60,76.33,77.07,77.80
4,0.48,64.13,NaN,64.87,NaN,65.60,NaN,66.33,NaN,67.07,NaN,67.80,NaN,68.53,NaN,69.27,NaN,NaN,70.00,NaN,70.73,NaN,71.47,NaN,72.20,72.93,73.67,74.40,75.13,75.87,76.60,77.33,78.07
5,0.49,64.40,NaN,65.13,NaN,65.87,NaN,66.60,NaN,67.33,NaN,68.07,NaN,68.80,NaN,69.53,NaN,NaN,70.27,NaN,71.00,NaN,71.73,NaN,72.47,73.20,73.93,74.67,75.40,76.13,76.87,77.60,78.33
6,0.50,64.67,NaN,65.40,NaN,66.13,NaN,66.87,NaN,67.60,NaN,68.33,NaN,69.07,NaN,69.80,NaN,NaN,70.53,NaN,71.27,NaN,72.00,NaN,72.73,73.47,74.20,74.93,75.67,76.40,77.13,77.87,78.60
7,0.51,64.93,NaN,65.67,NaN,66.40,NaN,67.13,NaN,67.87,NaN,68.60,NaN,69.33,NaN,70.07,NaN,NaN,70.80,NaN,71.53,NaN,72.27,NaN,73.00,73.73,74.47,75.20,75.93,76.67,77.40,78.13,78.87
8,0.52,65.20,NaN,65.93,NaN,66.67,NaN,67.40,NaN,68.13,NaN,68.87,NaN,69.60,NaN,70.33,NaN,NaN,71.07,NaN,71.80,NaN,72.53,NaN,73.27,74.00,74.73,75.47,76.20,76.93,77.67,78.40,79.13
9,0.53,65.47,NaN,66.20,NaN,66.93,NaN,67.67,NaN,68.40,NaN,69.13,NaN,69.87,NaN,70.60,NaN,NaN,71.33,NaN,72.07,NaN,72.80,NaN,73.53,74.27,75.00,75.73,76.47,77.20,77.93,78.67,79.40
10,0.54,65.73,NaN,66.47,NaN,67.20,NaN,67.93,NaN,68.67,NaN,69.40,NaN,70.13,NaN,70.87,NaN,NaN,71.60,NaN,72.33,NaN,73.07,NaN,73.80,74.53,75.27,76.00,76.73,77.47,78.20,78.93,79.67
11,0.55,66.00,NaN,66.73,NaN,67.47,NaN,68.20,NaN,68.93,NaN,69.67,NaN,70.40,NaN,71.13,NaN,NaN,71.87,NaN,72.60,NaN,73.33,NaN,74.07,74.80,75.53,76.27,77.00,77.73,78.47,79.20,79.93
12,0.56,66.27,NaN,67.00,NaN,67.73,NaN,68.47,NaN,69.20,NaN,69.93,NaN,70.67,NaN,71.40,NaN,NaN,72.13,NaN,72.87,NaN,73.60,NaN,74.33,75.07,75.80,76.53,77.27,78.00,78.73,79.47,80.20
13,0.57,66.53,NaN,67.27,NaN,68.00,NaN,68.73,NaN,69.47,NaN,70.20,NaN,70.93,NaN,71.67,NaN,NaN,72.40,NaN,73.13,NaN,73.87,NaN,74.60,75.33,76.07,76.80,77.53,78.27,79.00,79.73,80.47
14,0.58,66.80,NaN,67.53,NaN,68.27,NaN,69.00,NaN,69.73,NaN,70.47,NaN,71.20,NaN,71.93,NaN,NaN,72.67,NaN,73.40,NaN,74.13,NaN,74.87,75.60,76.33,77.07,77.80,78.53,79.27,80.00,80.73
15,0.59,67.07,NaN,67.80,NaN,68.53,NaN,69.27,NaN,70.00,NaN,70.73,NaN,71.47,NaN,72.20,NaN,NaN,72.93,NaN,73.67,NaN,74.40,NaN,75.13,75.87,76.60,77.33,78.07,78.80,79.53,80.27,81.00
16,0.60,67.33,NaN,68.07,NaN,68.80,NaN,69.53,NaN,70.27,NaN,71.00,NaN,71.73,NaN,72.47,NaN,NaN,73.20,NaN,73.93,NaN,74.67,NaN,75.40,76.13,76.87,77.60,78.33,79.07,79.80,80.53,81.27
17,0.61,67.60,NaN,68.33,NaN,69.07,NaN,69.80,NaN,70.53,NaN,71.27,NaN,72.00,NaN,72.73,NaN,NaN,73.47,NaN,74.20,NaN,74.93,NaN,75.67,76.40,77.13,77.87,78.60,79.33,80.07,80.80,81.53
18,0.62,67.87,NaN,68.60,NaN,69.33,NaN,70.07,NaN,70.80,NaN,71.53,NaN,72.27,NaN,73.00,NaN,NaN,73.73,NaN,74.47,NaN,75.20,NaN,75.93,76.67,77.40,78.13,78.87,79.60,80.33,81.07,81.80
19,0.63,68.13,NaN,68.87,NaN,69.60,NaN,70.33,NaN,71.07,NaN,71.80,NaN,72.53,NaN,73.27,NaN,NaN,74.00,NaN,74.73,NaN,75.47,NaN,76.20,76.93,77.67,78.40,79.13,79.87,80.60,81.33,82.07
20,0.64,68.40,NaN,69.13,NaN,69.87,NaN,70.60,NaN,71.33,NaN,72.07,NaN,72.80,NaN,73.53,NaN,NaN,74.27,NaN,75.00,NaN,75.73,NaN,76.47,77.20,77.93,78.67,79.40,80.13,80.87,81.60,82.33
21,0.65,68.67,NaN,69.40,NaN,70.13,NaN,70.87,NaN,71.60,NaN,72.33,NaN,73.07,NaN,73.80,NaN,NaN,74.53,NaN,75.27,NaN,76.00,NaN,76.73,77.47,78.20,78.93,79.67,80.40,81.13,81.87,82.60
22,0.66,68.93,NaN,69.67,NaN,70.40,NaN,71.13,NaN,71.87,NaN,72.60,NaN,73.33,NaN,74.07,NaN,NaN,74.80,NaN,75.53,NaN,76.27,NaN,77.00,77.73,78.47,79.20,79.93,80.67,81.40,82.13,82.87
23,0.67,69.20,NaN,69.93,NaN,70.67,NaN,71.40,NaN,72.13,NaN,72.87,NaN,73.60,NaN,74.33,NaN,NaN,75.07,NaN,75.80,NaN,76.53,NaN,77.27,78.00,78.73,79.47,80.20,80.93,81.67,82.40,83.13
24,0.68,69.47,NaN,70.20,NaN,70.93,NaN,71.67,NaN,72.40,NaN,73.13,NaN,73.87,NaN,74.60,NaN,NaN,75.33,NaN,76.07,NaN,76.80,NaN,77.53,78.27,79.00,79.73,80.47,81.20,81.93,82.67,83.40
25,0.69,69.73,NaN,70.47,NaN,71.20,NaN,71.93,NaN,72.67,NaN,73.40,NaN,74.13,NaN,74.87,NaN,NaN,75.60,NaN,76.33,NaN,77.07,NaN,77.80,78.53,79.27,80.00,80.73,81.47,82.20,82.93,83.67

In [213]:
xdf = df_0.dropna(axis='columns')

In [214]:
xdf

,$ Per Lb.,70.0,71.0,72.0,73.0,74.0,75.0,76.0,77.0,78.0,79.0,80.0,81.0,82.0,83.0,84.0,85.0,86.0,87.0,88.0,89.0
1,0.45,63.33,64.07,64.80,65.53,66.27,67.00,67.73,68.47,69.20,69.93,70.67,71.40,72.13,72.87,73.60,74.33,75.07,75.80,76.53,77.27
2,0.46,63.60,64.33,65.07,65.80,66.53,67.27,68.00,68.73,69.47,70.20,70.93,71.67,72.40,73.13,73.87,74.60,75.33,76.07,76.80,77.53
3,0.47,63.87,64.60,65.33,66.07,66.80,67.53,68.27,69.00,69.73,70.47,71.20,71.93,72.67,73.40,74.13,74.87,75.60,76.33,77.07,77.80
4,0.48,64.13,64.87,65.60,66.33,67.07,67.80,68.53,69.27,70.00,70.73,71.47,72.20,72.93,73.67,74.40,75.13,75.87,76.60,77.33,78.07
5,0.49,64.40,65.13,65.87,66.60,67.33,68.07,68.80,69.53,70.27,71.00,71.73,72.47,73.20,73.93,74.67,75.40,76.13,76.87,77.60,78.33
6,0.50,64.67,65.40,66.13,66.87,67.60,68.33,69.07,69.80,70.53,71.27,72.00,72.73,73.47,74.20,74.93,75.67,76.40,77.13,77.87,78.60
7,0.51,64.93,65.67,66.40,67.13,67.87,68.60,69.33,70.07,70.80,71.53,72.27,73.00,73.73,74.47,75.20,75.93,76.67,77.40,78.13,78.87
8,0.52,65.20,65.93,66.67,67.40,68.13,68.87,69.60,70.33,71.07,71.80,72.53,73.27,74.00,74.73,75.47,76.20,76.93,77.67,78.40,79.13
9,0.53,65.47,66.20,66.93,67.67,68.40,69.13,69.87,70.60,71.33,72.07,72.80,73.53,74.27,75.00,75.73,76.47,77.20,77.93,78.67,79.40
10,0.54,65.73,66.47,67.20,67.93,68.67,69.40,70.13,70.87,71.60,72.33,73.07,73.80,74.53,75.27,76.00,76.73,77.47,78.20,78.93,79.67
11,0.55,66.00,66.73,67.47,68.20,68.93,69.67,70.40,71.13,71.87,72.60,73.33,74.07,74.80,75.53,76.27,77.00,77.73,78.47,79.20,79.93
12,0.56,66.27,67.00,67.73,68.47,69.20,69.93,70.67,71.40,72.13,72.87,73.60,74.33,75.07,75.80,76.53,77.27,78.00,78.73,79.47,80.20
13,0.57,66.53,67.27,68.00,68.73,69.47,70.20,70.93,71.67,72.40,73.13,73.87,74.60,75.33,76.07,76.80,77.53,78.27,79.00,79.73,80.47
14,0.58,66.80,67.53,68.27,69.00,69.73,70.47,71.20,71.93,72.67,73.40,74.13,74.87,75.60,76.33,77.07,77.80,78.53,79.27,80.00,80.73
15,0.59,67.07,67.80,68.53,69.27,70.00,70.73,71.47,72.20,72.93,73.67,74.40,75.13,75.87,76.60,77.33,78.07,78.80,79.53,80.27,81.00
16,0.60,67.33,68.07,68.80,69.53,70.27,71.00,71.73,72.47,73.20,73.93,74.67,75.40,76.13,76.87,77.60,78.33,79.07,79.80,80.53,81.27
17,0.61,67.60,68.33,69.07,69.80,70.53,71.27,72.00,72.73,73.47,74.20,74.93,75.67,76.40,77.13,77.87,78.60,79.33,80.07,80.80,81.53
18,0.62,67.87,68.60,69.33,70.07,70.80,71.53,72.27,73.00,73.73,74.47,75.20,75.93,76.67,77.40,78.13,78.87,79.60,80.33,81.07,81.80
19,0.63,68.13,68.87,69.60,70.33,71.07,71.80,72.53,73.27,74.00,74.73,75.47,76.20,76.93,77.67,78.40,79.13,79.87,80.60,81.33,82.07
20,0.64,68.40,69.13,69.87,70.60,71.33,72.07,72.80,73.53,74.27,75.00,75.73,76.47,77.20,77.93,78.67,79.40,80.13,80.87,81.60,82.33
21,0.65,68.67,69.40,70.13,70.87,71.60,72.33,73.07,73.80,74.53,75.27,76.00,76.73,77.47,78.20,78.93,79.67,80.40,81.13,81.87,82.60
22,0.66,68.93,69.67,70.40,71.13,71.87,72.60,73.33,74.07,74.80,75.53,76.27,77.00,77.73,78.47,79.20,79.93,80.67,81.40,82.13,82.87
23,0.67,69.20,69.93,70.67,71.40,72.13,72.87,73.60,74.33,75.07,75.80,76.53,77.27,78.00,78.73,79.47,80.20,80.93,81.67,82.40,83.13
24,0.68,69.47,70.20,70.93,71.67,72.40,73.13,73.87,74.60,75.33,76.07,76.80,77.53,78.27,79.00,79.73,80.47,81.20,81.93,82.67,83.40
25,0.69,69.73,70.47,71.20,71.93,72.67,73.40,74.13,74.87,75.60,76.33,77.07,77.80,78.53,79.27,80.00,80.73,81.47,82.20,82.93,83.67

In [7]:
dfs = tb.read_pdf(file, pages="1")

Got stderr: Mar 08, 2022 11:18:29 PM org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
WARNING: Using fallback font 'Times-Bold' for 'TimesNewRoman-Bold'

In [31]:
dfs[0]

,ADG =,2.00,2.25,2.50,2.75,3.00,3.25,3.50,3.75,4.00,4.25,4.50
0,Days on Feed,100.00,89.00,80.00,73.00,67.00,62.00,57.0,53.00,50.00,47.00,44.00
1,Months on Feed,3.33,2.96,2.67,2.42,2.22,2.05,1.9,1.78,1.67,1.57,1.48

## Using Regex and playing around with it

In [217]:
import re

In [219]:
s = 'foo123bar'

In [220]:
'123' in s

True

In [223]:
re.search(r' ... ', 'hello my name is bob ')

In [224]:
three_chars_re = re.compile(r' ... ')

In [225]:
three_chars_re.search(' your mom is awesome')

In [254]:
s = '90210tg asdhas a birthday on Feb 251th'

In [252]:
birthday = re.compile('\w+ \d+\w\w')

In [255]:
print(birthday.search(s))

<re.Match object; span=(29, 38), match='Feb 251th'>

In [240]:
s2 = 'sam has a birthday on March 3rd'

In [241]:
birthday.search(s2)

In [242]:
birthday2 = re.compile('\w+ \w+\w\w')

In [249]:
birthday2.search(s)

In [256]:
digitre = re.compile(r'[0-9]')

In [257]:
numbers = '123 45'

In [258]:
digitre.search(numbers)

In [259]:
non_one_re = re.compile(r'[2-9]')
non_one_re.search(numbers)

In [261]:
bobre= re.compile(r'b[ao]b')
bobre.search('bob')

In [262]:
bobre.search('bab')

In [264]:
bobre = re.compile(r'b[aow]+b')
bobre.search('bob')

In [266]:
bobre.search('baaaaaaaoooaoaoaoaowowowowb')

In [270]:
#had to remove the plus signal before the b
bobre = re.compile(r'b[aow]{2}b')
bobre.search('bob')

In [271]:
bobre = re.compile(r'b[aow]{1,2}b')
bobre.search('bob')

In [272]:
phonere = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')

In [273]:
phonere.search('my number is 123-456-1234')

In [276]:
#using {} is a repeater functions so its the same as the above code
phonere = re.compile(r'\d{3}-\d{3}-\d{4}')   
phonere.search('my number is 123-456-1234')

## Revation

In [277]:
file = '/Users/miriamcorona/Desktop/pdfs/Rev/healthnet-daily-agent-scorecard-report-2022-03-08.pdf'

In [278]:
dfs = tb.read_pdf(file, pages="1")

In [299]:
dfs[0]

        Agent ID alma.arteaga@healthnet.com
0           Date                 2022-03-08
1     Agent Name              Arteaga, Alma
2  Agent Profile     healthnet-enroll-agent

In [305]:
xdf.melt()

                     variable                       value
0                    Agent ID                    Agent ID
1                    Agent ID                        Date
2                    Agent ID                  Agent Name
3                    Agent ID               Agent Profile
4  alma.arteaga@healthnet.com  alma.arteaga@healthnet.com
5  alma.arteaga@healthnet.com                  2022-03-08
6  alma.arteaga@healthnet.com               Arteaga, Alma
7  alma.arteaga@healthnet.com      healthnet-enroll-agent

In [306]:
xdf = dfs[0]
xdf.index = xdf.index + 1
xdf_out = xdf.stack()
xdf_out.index = xdf_out.index.map('{0[1]}_{0[0]}'.format)
xdf_out.to_frame().T

,Agent ID_1,alma.arteaga@healthnet.com_1,Agent ID_2,alma.arteaga@healthnet.com_2,Agent ID_3,alma.arteaga@healthnet.com_3,Agent ID_4,alma.arteaga@healthnet.com_4
0,Agent ID,alma.arteaga@healthnet.com,Date,2022-03-08,Agent Name,"Arteaga, Alma",Agent Profile,healthnet-enroll-agent

In [280]:
dfs[1]

  Start  2022-03-08 3:02:08 PM
0   End  2022-03-08 6:12:38 PM

In [281]:
dfs[2]

                             KPI Agent Value Role Average  Role Rank  Goal
0           Online Time (Status)    01:32:13     00:51:40        8.0   NaN
1            Busy Time (Project)    00:00:00     00:00:00        1.0   NaN
2          Busy Time (Call Work)    00:10:44     00:20:18       15.0   NaN
3     On the Phone Time (Status)    01:07:42     00:41:56        8.0   NaN
4     Out to Lunch Time (Status)    00:00:00     00:00:00        1.0   NaN
5                    Online Time    03:07:51     03:00:04       11.0   NaN
6            Break Time (Status)    00:17:12     00:09:09       21.0   NaN
7          Meeting Time (Status)    00:00:00     00:57:00        1.0   NaN
8                      Idle Time    01:42:57     01:11:59       17.0   NaN
9              On the Phone Time    01:08:23     00:43:52        8.0   NaN
10                     Work Time    02:51:20     01:55:51        9.0   NaN
11                    Mail Count           0            0        1.0   NaN
12           Voice Handled Count          15          NaN        NaN   NaN
13   Inbound Voice Handled Count          10          NaN        NaN   NaN
14  Outbound Voice Handled Count           5          NaN        NaN   NaN
15                 Handled Count          15           15       11.0   NaN
16                  Ring Average    00:00:01     00:00:00       24.0   NaN
17                          RONA           0            0        1.0   NaN
18                          ROAA           0            0        1.0   NaN
19         In-Phone Time Average    00:03:55     00:01:28       23.0   NaN
20        Out-Phone Time Average    00:01:07     00:01:17       16.0   NaN
21  After Call Talk Time Average    00:00:43     00:12:37       19.0   NaN
22           Handle Time Average    00:04:38     00:14:05       21.0   NaN
23           Productive Time (%)          42           25        5.0   NaN
24                 Talk Time (%)          36           16        4.0   NaN
25                 Busy Time (%)           6            9       17.0   NaN

In [283]:
dfs = tb.read_pdf(file, pages="all")

In [285]:
dfs[3]

        Agent ID amber.urena@healthnet.com
0           Date                2022-03-08
1     Agent Name              Urena, Amber
2  Agent Profile    healthnet-enroll-agent

In [287]:
box = [8,10,25,26]
fc = 28.28
for i in range(0, len(box)):
   box[i] *= fc

## section below is fromt the medium article https://medium.com/towards-data-science/scrape-data-from-pdf-files-using-python-and-pdfquery-d033721c3b28
## preferred method as it output one csv for one pdf
## the area below is specifically for one pdf with all the files
## need to research how to do to do multiple pdfs in one folder

In [340]:
#reading the pdf into the variable pdf from the file path above
pdf = pdfquery.PDFQuery(file)
#loading the pdf
pdf.load()
#converting the pdf to XML because it defines a set of rules for encoding pdf in a format that is readable.
#it It includes both data (actual SSN number) and metadata (e.g., text box coordination, height, width, etc.)
pdf.tree.write('pdfXML.txt', pretty_print = True)

In [341]:
#testing it out by choosing a set of coordinates
pdf.pq('LTTextLineHorizontal:overlaps_bbox("39.84, 713.021, 134.129, 821.568")').text()

'Alma Arteaga Agent ID Date Agent Name Agent Profile Amber Urena Agent ID Date Agent Name Agent Profile anais cardenas Agent Profile Agent ID Date Agent Name Angelica Flores Agent Profile Agent ID Date Agent Name Arianna Luna Agent ID Date Agent Name Agent Profile Carolina Reyes Agent Profile Agent ID Date Agent Name Christina Cisneros Agent Profile Agent ID Date Agent Name Cinthya Vasquez Agent Profile Agent ID Date Agent Name Cristina Rivera Agent ID Date Agent Name Agent Profile Daniel Silva Agent ID Date Agent Name Agent Profile Elza Aguirre Agent ID Date Agent Name Agent Profile Jennifer Martinez Agent Profile Agent ID Date Agent Name Jorge Nolasco Agent ID Date Agent Name Agent Profile Jose Penate Agent ID Date Agent Name Agent Profile Agent Scorecard (juanita.l.serrato@healthnet.com) Agent Profile Agent ID Date Agent Name Robert Martin Agent ID Date Agent Name Agent Profile Kevin Argueta Agent ID Date Agent Name Agent Profile Agent Scorecard (laura.n.cabrera@healthnet.com) Agent Profile Agent ID Date Agent Name Miguel Rodriguez Agent Profile Agent ID Date Agent Name Mildred Siracusa Agent Profile Agent ID Date Agent Name Myrna Vazquez Agent Profile Agent ID Date Agent Name Paul Friel Agent ID Date Agent Name Agent Profile Rosie Nunez Agent ID Date Agent Name Agent Profile Roy Garcia Agent ID Date Agent Name Agent Profile Saadia Orantes-Lopez Agent Profile Agent ID Date Agent Name Stephanie Tejada Agent Profile Agent ID Date Agent Name Tony De La Hoya Agent Profile Agent ID Date Agent Name Zach Thomas Agent ID Date Agent Name Agent Profile'

In [329]:
#testing it out by choosing a set of coordinates
pdf.pq('LTTextLineHorizontal:overlaps_bbox("39.84, 713.021, 134.129, 821.568")').text()

'Alma Arteaga Agent ID Date Agent Name Agent Profile Amber Urena Agent ID Date Agent Name Agent Profile anais cardenas Agent Profile Agent ID Date Agent Name Angelica Flores Agent Profile Agent ID Date Agent Name Arianna Luna Agent ID Date Agent Name Agent Profile Carolina Reyes Agent Profile Agent ID Date Agent Name Christina Cisneros Agent Profile Agent ID Date Agent Name Cinthya Vasquez Agent Profile Agent ID Date Agent Name Cristina Rivera Agent ID Date Agent Name Agent Profile Daniel Silva Agent ID Date Agent Name Agent Profile Elza Aguirre Agent ID Date Agent Name Agent Profile Jennifer Martinez Agent Profile Agent ID Date Agent Name Jorge Nolasco Agent ID Date Agent Name Agent Profile Jose Penate Agent ID Date Agent Name Agent Profile Agent Scorecard (juanita.l.serrato@healthnet.com) Agent Profile Agent ID Date Agent Name Robert Martin Agent ID Date Agent Name Agent Profile Kevin Argueta Agent ID Date Agent Name Agent Profile Agent Scorecard (laura.n.cabrera@healthnet.com) Agent Profile Agent ID Date Agent Name Miguel Rodriguez Agent Profile Agent ID Date Agent Name Mildred Siracusa Agent Profile Agent ID Date Agent Name Myrna Vazquez Agent Profile Agent ID Date Agent Name Paul Friel Agent ID Date Agent Name Agent Profile Rosie Nunez Agent ID Date Agent Name Agent Profile Roy Garcia Agent ID Date Agent Name Agent Profile Saadia Orantes-Lopez Agent Profile Agent ID Date Agent Name Stephanie Tejada Agent Profile Agent ID Date Agent Name Tony De La Hoya Agent Profile Agent ID Date Agent Name Zach Thomas Agent ID Date Agent Name Agent Profile'

In [337]:
#this box would be where i would grab coordinates from the xml file plug them in here to see what would populate
pdf.pq('LTTextLineHorizontal:overlaps_bbox("200.352, 332.456, 211.047, 346.778")').text()

'10 0 0 9 0 4 0 6 3 0 8 7 16 0 0 8 0 9 0 20 7 0 5 0 12 0 10 0'

In [338]:
#once the desired coordinates are figured out choose variables to assign the contents of the coordinates into
#function below is specific to the pdf file for revation since those coordinates reflect what is in the pdf


def pdfscrape(pdf):
    # Extract each relevant information individually
    name              = pdf.pq('LTTextLineHorizontal:overlaps_bbox("148.896, 733.757, 220.15, 750.683")').text()
    date              = pdf.pq('LTTextLineHorizontal:overlaps_bbox("148.896, 754.493, 206.832, 771.419")').text()
    starttime         = pdf.pq('LTTextLineHorizontal:overlaps_bbox("174.24, 656.552, 273.427, 670.874")').text()
    endtime           = pdf.pq('LTTextLineHorizontal:overlaps_bbox("174.24, 631.976, 273.427, 646.298")').text()
    onlinetime        = pdf.pq('LTTextLineHorizontal:overlaps_bbox("200.352, 572.072, 238.191, 586.394")').text()
    breaktime         = pdf.pq('LTTextLineHorizontal:overlaps_bbox("200.352, 461.48, 238.191, 475.802")').text()
    inboundcalls      = pdf.pq('LTTextLineHorizontal:overlaps_bbox("200.352, 332.456, 211.047, 346.778")').text()
# Combined all relevant information into single observation
# creating a pandas data frame to assign the variables above to specific columns labeled after the variables
    page = pd.DataFrame({
                         'name': name,
                         'date': date,
                         'starttime': starttime,
                         'endtime': endtime,
                         'onlinetime': onlinetime,
                         'breaktime': breaktime,
                         'inboundcalls': inboundcalls
                       }, index=[0])
    return(page)

In [339]:
#the code below gets the number of pages in the pdf file and
pagecount = pdf.doc.catalog['Pages'].resolve()['Count']


master = pd.DataFrame()
#the for loop is now going to go into every page in the pdf
for p in range(pagecount):
    #loading that speficic page from the pdf
    pdf.load(p)
    #scraping the contents of that specific page
    page = pdfscrape(pdf) 
    #appending everything to the master pandas dataframe so everything is in one pandas frame
    master = master.append(page, ignore_index=True)
#exporting to a csv file    
master.to_csv('output.csv', index = False)

In [342]:
pagecount

28